### ISSUE TITLE
Navigate easily through the website

### ISSUE THREAD

**Issue by jeromeabel** [jeromeabel/medito-fundraising#2]
## Description
- **As a** new user
- **I want** to navigate easily through each page 
- **So that** I can view all content in a consistent design

## Acceptance criteria n°1
- **Given** I'm a new user
- **When** I go the home page
- **Then** I see a menu navigation

## Acceptance criteria n°2
- **Given** I'm a new user
- **When** I click on a link in the menu
- **Then** a new page is loaded

## Tasks
- [x] Basic files structure: maintainable
- [x] Basic CSS: clear, and consistent
- [x] Common layout : Header, Navigation, Footer
- [x] Home page
- [x] Error page
- [x] About page
- [x] Projects page
