### ISSUE TITLE
See the details of a project

### ISSUE THREAD

**Issue by jeromeabel** [jeromeabel/medito-fundraising#3]
## Description
- **As a** future donor
- **I want** to understand the project and objectives
- **So that** I could choose this project

## Acceptance criteria
- **Given** I'm on the home page
- **When** I click on a project's link 
- **Then** a page is opened with all details

## Tasks
- [x] Route page / project
- [x] Display data of the project: title, description, goal
- [x] Refacto query & API routes
- [x] See image, title, date, description, and text content
