### ISSUE TITLE
See the list of campaigns

### ISSUE THREAD

**Issue by jeromeabel** [jeromeabel/medito-fundraising#4]
## Description
- **As a** a future donor
- **I want** to see the list of campaigns
- **So that** I could choose my campaign

## Acceptance criteria
- **Given** 
- **When**  I'm on the home page
- **Then** I should see a list of all campaigns

## Tasks
- [x] Minimal set of data modeling: campaigns, donors, questions (theme, rewards will come after if needed)
- [x] Setup and fill a database: implementation of supabase
- [x] Minimal command to list campaigns from the database
- [x] Setup Cloudflare and Astro to be server side rendered, and deployed
