### ISSUE TITLE
See the Questions and answers of a project

### ISSUE THREAD

**Issue by jeromeabel** [jeromeabel/medito-fundraising#5]
## Description
- **As a**
- **I want**
- **So that**

## Acceptance criteria
- **Given**
- **When**
- **Then**

## Tasks
- [x] Add data to supabase
- [x] Create API endpoints to get Questions for one campaign
- [x] Create Dropdown component with React and animations
